[main]
font=JetBrainsMono Nerd Font Mono:size=9.25
pad=0x0
resize-by-cells=yes

[cursor]
style=beam
blink=yes
beam-thickness=1.2

[colors-dark]
foreground=E6E6E6
background=0B0D10

selection-foreground=FFFFFF
selection-background=1C1F26

# normal colors
regular0=1C1F26
regular1=FF6B6B
regular2=98C379
regular3=E5C07B
regular4=5F87FF
regular5=C678DD
regular6=56B6C2
regular7=E6E6E6

# bright colors
bright0=4A4F58
bright1=FF7B7B
bright2=A8D98C
bright3=F0D48A
bright4=6F97FF
bright5=D18CE8
bright6=66C6D2
bright7=FFFFFF

# alpha=0.75
