# Feel free to write your user preferences here.
# so any settings here will override those in hyprland.conf
# you can add your prefered bindings here as well, but for better organization,
# for descriptions, refer to the comments next to each binding in keybindings.conf
# eg., bind = MOD, KEY, ACTION, ARGUMENT # Description
# Happy Hyprlanding!